# _config.yml

title: Judul Blog Anda
description: "Deskripsi singkat dan menarik tentang blog Anda."
url: "https://finclique.github.io"
logo: /assets/images/logo.png

# PERUBAHAN 1: Menambahkan informasi Author untuk Author Box
author:
  name: Nama Lengkap Anda
  avatar: /assets/images/nama-foto-profil.jpg # <-- Ganti dengan path ke foto Anda
  bio: "Tulis deskripsi singkat tentang diri Anda di sini. Deskripsi ini akan muncul di bawah setiap artikel."

# PERUBAHAN 2: Mengubah struktur URL postingan menjadi /judul-postingan/
permalink: /:slug/
highlighter: rouge

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-paginate

# Konfigurasi Pagination (tetap sama)
paginate: 6
paginate_path: "/page/:num/"

# 1. Beritahu Jekyll tentang folder '_tools' Anda
collections:
  tools:
    output: false

# 2. Beritahu Jekyll untuk tidak mengabaikan folder 'pages'
include:
  - pages


